# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aha < Formula
  desc "A TUI for showing dependencies of a Python project"
  homepage "https://github.com/suntianxun/aha"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suntianxun/aha/releases/download/v0.2.0/aha_0.2.0_darwin_amd64.tar.gz"
      sha256 "35c1a3f4260a288ebca6fec6c93e9f24834f3abc45eda349fdc1de188af001df"

      define_method(:install) do
        bin.install "aha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suntianxun/aha/releases/download/v0.2.0/aha_0.2.0_darwin_arm64.tar.gz"
      sha256 "27d269fef0fbf028f1f5e0eb8ce4142269cab824f1ac06e1b9e15488362104d9"

      define_method(:install) do
        bin.install "aha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suntianxun/aha/releases/download/v0.2.0/aha_0.2.0_linux_amd64.tar.gz"
      sha256 "ab7373f1e1baa9c0dfedb732c788b79f9a7b2f78a6905c1cba34b8d49d9cbf10"
      define_method(:install) do
        bin.install "aha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suntianxun/aha/releases/download/v0.2.0/aha_0.2.0_linux_arm64.tar.gz"
      sha256 "a4ed2561403270df91b044e8843628d678551db1d7692d7454a281cd39d1cf9c"
      define_method(:install) do
        bin.install "aha"
      end
    end
  end

  test do
    assert_match "Usage:", shell_output("#{bin}/aha 2>&1", 1)
  end
end
