# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aha < Formula
  desc "A TUI for showing dependencies of a Python project"
  homepage "https://github.com/suntianxun/aha"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suntianxun/aha/releases/download/v0.1.0/aha_0.1.0_darwin_amd64.tar.gz"
      sha256 "5319dd8fd48a7fe3c82ccae66fbce9e699321e6b2abf6f7470de6125a068b4e9"

      define_method(:install) do
        bin.install "aha"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suntianxun/aha/releases/download/v0.1.0/aha_0.1.0_darwin_arm64.tar.gz"
      sha256 "808916fe6a36985e70319b96c815a0653ff8c8ffe3236c0e45c78d60f87d594a"

      define_method(:install) do
        bin.install "aha"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suntianxun/aha/releases/download/v0.1.0/aha_0.1.0_linux_amd64.tar.gz"
      sha256 "07e05d6e2ebe95424384e3a796fa6743c5621a6c63b03c748409a81247c73977"
      define_method(:install) do
        bin.install "aha"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suntianxun/aha/releases/download/v0.1.0/aha_0.1.0_linux_arm64.tar.gz"
      sha256 "d197a85b1eab1aed6c4d002383db5df9bf3153ef9f78b610d93c6c1b16dd3d39"
      define_method(:install) do
        bin.install "aha"
      end
    end
  end

  test do
    assert_match "Usage:", shell_output("#{bin}/aha 2>&1", 1)
  end
end
