# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hmm < Formula
  desc "A terminal UI for viewing CSV and Parquet files"
  homepage "https://github.com/suntianxun/hmm"
  version "2.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suntianxun/hmm/releases/download/v2.1.3/hmm_2.1.3_darwin_amd64.tar.gz"
      sha256 "e092966f52cfee1dfa0e84154174c49334c7c7d561ccdd33305d6bfc074516c3"

      define_method(:install) do
        bin.install "hmm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suntianxun/hmm/releases/download/v2.1.3/hmm_2.1.3_darwin_arm64.tar.gz"
      sha256 "30200146025e1deb2dc126ca192ec67e99b44d5feafb386d3661611ad19811db"

      define_method(:install) do
        bin.install "hmm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suntianxun/hmm/releases/download/v2.1.3/hmm_2.1.3_linux_amd64.tar.gz"
      sha256 "34b4b61efd0dc8db03bab07498067f638241a9a3ebf6e8350689cbf6928681b8"
      define_method(:install) do
        bin.install "hmm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suntianxun/hmm/releases/download/v2.1.3/hmm_2.1.3_linux_arm64.tar.gz"
      sha256 "88a7de2f49b28d320a8352c06e170c768072768e0e76160d93953b9a031272af"
      define_method(:install) do
        bin.install "hmm"
      end
    end
  end
end
