# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hmm < Formula
  desc "A terminal UI for viewing CSV and Parquet files"
  homepage "https://github.com/suntianxun/hmm"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suntianxun/hmm/releases/download/v0.1.4/hmm_0.1.4_darwin_amd64.tar.gz"
      sha256 "7a497035f79267c6319d92622d3eda25302892b149c391adcc6d05691f0b8352"

      define_method(:install) do
        bin.install "hmm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suntianxun/hmm/releases/download/v0.1.4/hmm_0.1.4_darwin_arm64.tar.gz"
      sha256 "f004239247cefcaa5d16be6b0bd7bf11778d81558ae3c35b2e26fb14a8a99b09"

      define_method(:install) do
        bin.install "hmm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suntianxun/hmm/releases/download/v0.1.4/hmm_0.1.4_linux_amd64.tar.gz"
      sha256 "899474a0cea8f93f9ce4142aea32b6c1db6b2ae7f3e9d4dc6943462dc53aadb7"
      define_method(:install) do
        bin.install "hmm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suntianxun/hmm/releases/download/v0.1.4/hmm_0.1.4_linux_arm64.tar.gz"
      sha256 "f1310089094b60acefd148f03b4138e7ddd4533c9cf3c39976415a5e3f612abb"
      define_method(:install) do
        bin.install "hmm"
      end
    end
  end
end
