# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bruh < Formula
  desc "A beautiful terminal user interface for Homebrew"
  homepage "https://github.com/suntianxun/bruh"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suntianxun/bruh/releases/download/v0.1.3/bruh_0.1.3_darwin_amd64.tar.gz"
      sha256 "6c01a0923f6833502c9fda3232c32ee5eacb1df69abdfe6607f5997069c22319"

      define_method(:install) do
        bin.install "bruh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suntianxun/bruh/releases/download/v0.1.3/bruh_0.1.3_darwin_arm64.tar.gz"
      sha256 "beba2ad383caa5e91f8ceb2e1c5d5ae60ba17faa68565db919c3bc1bd4701ab8"

      define_method(:install) do
        bin.install "bruh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suntianxun/bruh/releases/download/v0.1.3/bruh_0.1.3_linux_amd64.tar.gz"
      sha256 "09164c482a97a2fee5c97b649b8f73bc898cc9f54caaf09d97a91414657589a0"
      define_method(:install) do
        bin.install "bruh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suntianxun/bruh/releases/download/v0.1.3/bruh_0.1.3_linux_arm64.tar.gz"
      sha256 "824b2c0f01462aab196d7e20dab176f5497a8632bcea93785896bd8ddcaf8f56"
      define_method(:install) do
        bin.install "bruh"
      end
    end
  end
end
