# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bruh < Formula
  desc "A beautiful terminal user interface for Homebrew"
  homepage "https://github.com/suntianxun/bruh"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suntianxun/bruh/releases/download/v0.1.2/bruh_0.1.2_darwin_amd64.tar.gz"
      sha256 "16b913798a007d8f60e274d254f82a0cdf0c14908436ffc10e59b436337545e3"

      define_method(:install) do
        bin.install "bruh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suntianxun/bruh/releases/download/v0.1.2/bruh_0.1.2_darwin_arm64.tar.gz"
      sha256 "3401be774c4f40c27e90de8cd80ea212b00ba2fee582ffa210e3adcdfc825236"

      define_method(:install) do
        bin.install "bruh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suntianxun/bruh/releases/download/v0.1.2/bruh_0.1.2_linux_amd64.tar.gz"
      sha256 "b60f1e4f6064d20cac13653e9f32a5a7c099e8117c909c25fa7e7b9d8571c334"
      define_method(:install) do
        bin.install "bruh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suntianxun/bruh/releases/download/v0.1.2/bruh_0.1.2_linux_arm64.tar.gz"
      sha256 "29f8ab19690d598e2b47f0651402dff909104fa5f62b0d0f6825a064d3f54d95"
      define_method(:install) do
        bin.install "bruh"
      end
    end
  end
end
